openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:5001/swagger/v1/swgger.json
paths:
  /api/listingid:
    get:
      responses:
        '200':
          description: OK